repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff
      - id: ruff-format
        files: ./server/
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        files: ./server/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.0-alpha.0
    hooks:
      - id: eslint
        files: ^client/
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-plugin-import
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - eslint-plugin-react-refresh
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^client/
        additional_dependencies:
          - prettier
